import json

cells = [
    # Cell 1: Installation
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "install_cell"},
        "outputs": [],
        "source": [
            "# Cell 1: Install all required dependencies quietly\n",
            "!pip install -q FlagEmbedding sentence-transformers fastapi uvicorn pyngrok pydantic docling nest_asyncio"
        ]
    },
    # Cell 2: Imports
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "imports_cell"},
        "outputs": [],
        "source": [
            "# Cell 2: Imports\n",
            "import os\n",
            "import tempfile\n",
            "import asyncio\n",
            "import uvicorn\n",
            "import nest_asyncio\n",
            "from typing import List\n",
            "from pydantic import BaseModel\n",
            "from fastapi import FastAPI, UploadFile, File, HTTPException\n",
            "from pyngrok import ngrok\n",
            "\n",
            "from FlagEmbedding import BGEM3FlagModel\n",
            "from sentence_transformers import CrossEncoder\n",
            "\n",
            "from docling.datamodel.base_models import InputFormat\n",
            "from docling.datamodel.pipeline_options import PdfPipelineOptions\n",
            "from docling.document_converter import DocumentConverter, PdfFormatOption\n"
        ]
    },
    # Cell 3: Load Models
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "models_cell"},
        "outputs": [],
        "source": [
            "# Cell 3: Initialize Models & Converters on GPU\n",
            "print(\"🚀 Initializing GPU Models & Converters...\")\n",
            "\n",
            "# 1. BGE-M3 Dense+Sparse Embedding Model\n",
            "print(\"1️⃣ Loading BGE-M3 Embedding Model...\")\n",
            "embedding_model = BGEM3FlagModel('BAAI/bge-m3', use_fp16=True)\n",
            "\n",
            "# 2. BGE Reranker v2 m3 Model (CrossEncoder for maximum stability)\n",
            "print(\"2️⃣ Loading BGE Reranker v2 m3 Model...\")\n",
            "reranker = CrossEncoder('BAAI/bge-reranker-v2-m3', max_length=512)\n",
            "\n",
            "# 3. Fast Docling PDF Converter (No OCR)\n",
            "print(\"3️⃣ Initializing Fast Docling PDF Converter...\")\n",
            "pipeline_options = PdfPipelineOptions()\n",
            "pipeline_options.do_ocr = False\n",
            "pipeline_options.do_table_structure = True\n",
            "\n",
            "docling_converter = DocumentConverter(\n",
            "    format_options={\n",
            "        InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)\n",
            "    }\n",
            ")\n",
            "\n",
            "print(\"✅ All Models Loaded Successfully!\")\n"
        ]
    },
    # Cell 4: FastAPI App & Endpoints
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "fastapi_cell"},
        "outputs": [],
        "source": [
            "# Cell 4: FastAPI Application & Microservice Endpoints\n",
            "app = FastAPI(title=\"Clinical RAG GPU Microservice\")\n",
            "\n",
            "\n",
            "class EmbedRequest(BaseModel):\n",
            "    texts: List[str]\n",
            "\n",
            "\n",
            "class RerankRequest(BaseModel):\n",
            "    query: str\n",
            "    documents: List[str]\n",
            "\n",
            "\n",
            "@app.get(\"/\")\n",
            "@app.get(\"/health\")\n",
            "def health():\n",
            "    return {\n",
            "        \"status\": \"healthy\",\n",
            "        \"models\": [\"BAAI/bge-m3\", \"BAAI/bge-reranker-v2-m3\", \"Docling-PDF\"],\n",
            "        \"ready\": True\n",
            "    }\n",
            "\n",
            "\n",
            "@app.post(\"/embed\")\n",
            "def embed(req: EmbedRequest):\n",
            "    if not req.texts:\n",
            "        return {\"dense\": [], \"sparse\": [], \"dense_size\": 1024}\n",
            "\n",
            "    out = embedding_model.encode(\n",
            "        req.texts,\n",
            "        return_dense=True,\n",
            "        return_sparse=True,\n",
            "        return_colbert_vecs=False\n",
            "    )\n",
            "\n",
            "    dense_vecs = [v.tolist() for v in out['dense_vecs']]\n",
            "    sparse_vecs = []\n",
            "    for lex in out['lexical_weights']:\n",
            "        sparse_vecs.append({\n",
            "            \"indices\": [int(k) for k in lex.keys()],\n",
            "            \"values\": [float(v) for v in lex.values()]\n",
            "        })\n",
            "\n",
            "    return {\n",
            "        \"dense\": dense_vecs,\n",
            "        \"sparse\": sparse_vecs,\n",
            "        \"dense_size\": 1024\n",
            "    }\n",
            "\n",
            "\n",
            "@app.post(\"/rerank\")\n",
            "def rerank(req: RerankRequest):\n",
            "    if not req.documents:\n",
            "        return {\"scores\": []}\n",
            "\n",
            "    pairs = [[req.query, doc] for doc in req.documents]\n",
            "    scores = reranker.predict(pairs)\n",
            "    return {\"scores\": [float(s) for s in scores]}\n",
            "\n",
            "\n",
            "@app.post(\"/parse_pdf\")\n",
            "async def parse_pdf(file: UploadFile = File(...)):\n",
            "    if not file.filename.lower().endswith(\".pdf\"):\n",
            "        raise HTTPException(status_code=400, detail=\"Only PDF files allowed\")\n",
            "\n",
            "    with tempfile.NamedTemporaryFile(delete=False, suffix=\".pdf\") as tmp:\n",
            "        content = await file.read()\n",
            "        tmp.write(content)\n",
            "        tmp_path = tmp.name\n",
            "\n",
            "    try:\n",
            "        print(f\"📄 Starting Docling GPU Parsing for: {file.filename}...\")\n",
            "        loop = asyncio.get_running_loop()\n",
            "        result = await loop.run_in_executor(None, docling_converter.convert, tmp_path)\n",
            "        doc = result.document\n",
            "\n",
            "        total_pages = getattr(doc, \"num_pages\", 1)\n",
            "        sections = []\n",
            "        tables = []\n",
            "        figures = []\n",
            "\n",
            "        if hasattr(doc, \"texts\"):\n",
            "            for item in doc.texts:\n",
            "                text_str = str(getattr(item, \"text\", \"\") or \"\")\n",
            "                if text_str.strip():\n",
            "                    sections.append({\n",
            "                        \"page_no\": int(getattr(item, \"page_no\", 1) or 1),\n",
            "                        \"section_name\": str(getattr(item, \"section_header\", \"\") or \"\"),\n",
            "                        \"text\": text_str\n",
            "                    })\n",
            "\n",
            "        if hasattr(doc, \"tables\"):\n",
            "            for tbl in doc.tables:\n",
            "                caption = str(getattr(tbl, \"caption\", \"\") or \"\")\n",
            "                headers_list = []\n",
            "                rows_list = []\n",
            "                tbl_text = f\"Table: {caption}\"\n",
            "\n",
            "                try:\n",
            "                    df = tbl.export_to_dataframe(doc=doc)\n",
            "                    if df is not None and not df.empty:\n",
            "                        tbl_text = df.to_markdown(index=False)\n",
            "                        headers_list = [str(col) for col in df.columns.tolist()]\n",
            "                        rows_list = [[str(val) for val in row] for row in df.values.tolist()]\n",
            "                except Exception:\n",
            "                    pass\n",
            "\n",
            "                tables.append({\n",
            "                    \"page_no\": int(getattr(tbl, \"page_no\", 1) or 1),\n",
            "                    \"caption\": caption,\n",
            "                    \"headers\": headers_list,\n",
            "                    \"rows\": rows_list,\n",
            "                    \"text_content\": tbl_text\n",
            "                })\n",
            "\n",
            "        if hasattr(doc, \"pictures\"):\n",
            "            for pic in doc.pictures:\n",
            "                caption = str(getattr(pic, \"caption\", \"\") or \"\")\n",
            "                figures.append({\n",
            "                    \"page_no\": int(getattr(pic, \"page_no\", 1) or 1),\n",
            "                    \"caption\": caption,\n",
            "                    \"text_content\": f\"Figure: {caption}\"\n",
            "                })\n",
            "\n",
            "        print(f\"✅ Finished Parsing! Total Pages: {total_pages} | Extracted: {len(sections)} sections, {len(tables)} tables\")\n",
            "\n",
            "        return {\n",
            "            \"total_pages\": total_pages,\n",
            "            \"sections\": sections,\n",
            "            \"tables\": tables,\n",
            "            \"figures\": figures\n",
            "        }\n",
            "\n",
            "    except Exception as e:\n",
            "        print(f\"❌ Docling GPU parsing error: {e}\")\n",
            "        raise HTTPException(status_code=500, detail=f\"Docling GPU parsing error: {str(e)}\")\n",
            "    finally:\n",
            "        if os.path.exists(tmp_path):\n",
            "            os.remove(tmp_path)\n"
        ]
    },
    # Cell 5: Server Execution & Pyngrok
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "server_cell"},
        "outputs": [],
        "source": [
            "# Cell 5: Start Pyngrok Tunnel & Uvicorn Server\n",
            "nest_asyncio.apply()\n",
            "\n",
            "# Kill existing tunnels\n",
            "ngrok.kill()\n",
            "\n",
            "# Open public tunnel on port 8000\n",
            "public_url = ngrok.connect(8000).public_url\n",
            "print(\"\\n\" + \"=\" * 60)\n",
            "print(f\"🚀 PUBLIC COLAB SERVICE URL: {public_url}\")\n",
            "print(f\"👉 Copy this URL into your local .env file:\")\n",
            "print(f\"   REMOTE_EMBEDDING_URL={public_url}\")\n",
            "print(f\"   REMOTE_DOCLING_URL={public_url}\")\n",
            "print(f\"   RERANKER_API_URL={public_url}\")\n",
            "print(\"=\" * 60 + \"\\n\")\n",
            "\n",
            "# Run Uvicorn app\n",
            "uvicorn.run(app, host=\"0.0.0.0\", port=8000)\n"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "colab": {
            "name": "clinical_embedding_endpoint.ipynb",
            "provenance": [],
            "gpuType": "T4"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

target_path = r"C:\Users\kimos\Downloads\clinical_embedding_endpoint.ipynb"
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"Successfully cleaned and updated notebook at: {target_path}")
